### PR TITLE
Revert "[CBRD-25097] Revise Isolation Testcase for PL/CSQL Phase-0 Branch Merge

### PR DESCRIPTION
**Pull request by LyhengCHHAY**
revert #1376. 
The reason for the revert is explained in the comment below.

### CODE REVIEW

**Review by kwonhoil — APPROVED** [review]

**Review by ssihil — APPROVED** [review]

**Comment by zionyun** [comment]
@LyhengCHHAY 
This PR is a rollback of the changes made in https://github.com/CUBRID/cubrid-testcases/pull/1728
In the future, if a similar situation arises where we need to revert changes from an earlier PR, it would be better to use the revert function instead of creating a new PR.

Also, has it been confirmed with the developer why [dba.t1] has been changed back to be output twice?

**Comment by LyhengCHHAY** [comment]
@zionyun 
Thank you for your advise, I'll will use the revert function in the future. 

Regarding the confirmation from the developer, I didn't connect with them yet. Would you mind to share their contact to me?

**Comment by LyhengCHHAY** [comment]
@hgryoo Hi Harry, this is Lyheng from CamQA. I'm working on CUBRID regression test now.

I tried to make a new PR for this isolation test case, however, this revision had been revised before.
(< | ERROR RETURNED: Semantic: DELETE is not authorized on dba.t1. delete [dba.t1] from [dba.t1] where [dba.t1].id=2 --- > | ERROR RETURNED: Semantic: DELETE is not authorized on dba.t1. delete [dba.t1] from [dba.t1] [dba.t1] where [dba.t1].id=2 )

May I know why [dba.t1] changed back to it previous output?

**Comment by hgryoo** [comment]
> @hgryoo Hi Harry, this is Lyheng from CamQA. I'm working on CUBRID regression test now.
> 
> I tried to make a new PR for this isolation test case, however, this revision had been revised before. (< | ERROR RETURNED: Semantic: DELETE is not authorized on dba.t1. delete [dba.t1] from [dba.t1] where [dba.t1].id=2 --- > | ERROR RETURNED: Semantic: DELETE is not authorized on dba.t1. delete [dba.t1] from [dba.t1] [dba.t1] where [dba.t1].id=2 )
> 
> May I know why [dba.t1] changed back to it previous output?

Hi, Lyheng.

In the FROM clause of a DELETE statement, the specified table name must have resolved name. During the PL/CSQL phase-0, this requirement was suppressed while revising the query parser. This suppression led to a bug where the PL/CSQL's DELETE static SQL could not be executed. Therefore, the logic suppressing the resolved name has been reverted.

According to the DELETE statement syntax in the CUBRID manual (https://www.cubrid.org/manual/en/11.3/sql/query/delete.html):
```
<DELETE single table>
DELETE [FROM] [schema_name.]table_name [ WHERE <search_condition> ] [LIMIT row_count]

<DELETE multiple tables FROM ...>
DELETE [schema_name.]table_name [{, [schema_name.]table_name}] FROM <table_specifications> [ WHERE <search_condition> ]

<DELETE FROM multiple tables USING ...>
DELETE FROM [schema_name.]table_name [{, [schema_name.]table_name}] USING <table_specifications> [ WHERE <search_condition> ]
```

In the case of deleting multiple tables (as shown in the second line), you can specify table alias names like this:

Original query
```
DELETE a, b FROM a_tbl a INNER JOIN b_tbl b ON a.id=b.id
INNER JOIN c_tbl c ON b.id=c.id;
```

Rewritten query (revised version)
```
select b,class b,a,class a from [dba.a_tbl] a, [dba.b_tbl] b, [dba.c_tbl] c where a.id=b.id and b.id=c.id
```

**In PL/CSQL, static SQLs (queries in the PL/CSQL body) use the rewritten query for execution.** If the resolved name (= alias name) is suppressed, it causes a parsing error, leading to the failure of the PL/CSQL program execution.

Example of rewritten query (bug version)
```
select b,class b,a,class a from [dba.a_tbl], [dba.b_tbl], [dba.c_tbl] where a.id=b.id and b.id=c.id
```

The above rewritten query shows an syntax error in PL/CSQL program: `Attribute "b" was not found.`

**Review by zionyun — APPROVED** [review]

**Pull request merged**
