### PR TITLE
[CUBRIDQA-1237] Testcase modification for missing deallocate or drop on prepared statement.

### PR DESCRIPTION
**Pull request by kimhak-tech**
Add "deallocate" statement to the testcases that are missing. 

Refer to http://jira.cubrid.org/browse/CUBRIDQA-1237

### CODE REVIEW

**Comment by kimhak-tech** [comment]
The first commit contains the revise testcases from testcase number 1 to number 40 that mentioned on the excel file deallocate_missing.xlsx on ticket CUBRIDQA-1237

**Comment by kimhak-tech** [comment]
The second commmit contains the modification from row 40 to 118. Refer to the detail on file deallocate_missing _revision_update.xlsx on ticket CUBRIDQA-1237.

**Comment by ssihil** [comment]
> The second commmit contains the modification from row 40 to 118. Refer to the detail on file deallocate_missing _revision_update.xlsx on ticket CUBRIDQA-1237.

It looks like the relevant file is deallocate_missing.xlsx and not deallocate_missing_revision_update.xlsx.

**Comment by kimhak-tech** [comment]
> > The second commmit contains the modification from row 40 to 118. Refer to the detail on file deallocate_missing _revision_update.xlsx on ticket CUBRIDQA-1237.
> 
> It looks like the relevant file is deallocate_missing.xlsx and not deallocate_missing_revision_update.xlsx.

Both files share the same testcases. However on deallocate_missing_revision_update.xlsx, I have updated the status and add some new testcases that I found missing.

**Review by kwonhoil — APPROVED** [review]

**Review by tw-kang — APPROVED** [review]

**Comment by kimhak-tech** [comment]
The last commit contains testcases from row 119 to 283, has been pushed.

**Review by tw-kang — APPROVED** [review]

**Pull request merged**
